### ISSUE TITLE
주제 결정하기

### ISSUE THREAD

**Issue by SaeromB** [dataitgirls2/m3#3]
1. 강남역 유동인구 (신분당선 개통 전후) 의 변화, 상권변화
2. 날씨에 따른 지출 항목의 변화
3. 1인가구와 1인가구 소비량의 증가에 따른 1인가구 상권분석(미리 뜰 상권?, 1인가구에 맞는 상권?) 
4. 초복부터 말복까지 온도변화와 산업전기료의 관계(가계의 온도 변화에 따른 매출액의 변화 확인)
5. 온도 변화에 따른 배달음식 주문량 (콜 수)
6. 소확행 (직장인들이 많은 곳에 힐링할 상권이 어떻게 분포되어 있는가?)
7. 지역별 카페매장의 색감분석
8. 지역별 정신과 병원, 휴식시설의 분포

**Comment by jyw7664** [comment]
**결정된 주제입니다!**  :muscle: 
**1. <색감> 서울시 카페상권의 색감분석**
(지역적 특색이 있는가?, 색감이 갖는 사회학적 의미와 연관지을수 있을까?)
**2. <배달> 날씨, 기온에 따른 서울시 배달상권분석**
